Fix breaking changes in Neotest XML library
rouge8/neotest-rust pull request #18
Opened 2022-12-15 17:28 UTC by andy-bell101

Thanks for the plugin

I noticed today that I couldn't run my tests anymore since there's been a breaking change in Neotest's XML parsing library. Thought I'd give back by making the fix. 

There's some other changes of mine in there to handle multiple test suites and filter out src files from the list of test files if there are no tests. Feel free to drop those.

2022-12-15 18:13 UTC, andy-bell101 commented
Yeah sure should have that done by tonight

2022-12-15 19:24 UTC, andy-bell101 commented
Not entirely sure how to go about testing the results parser. I was hoping there would be some existing tests that I could copy-paste but looks like that parts untested at the moment

2022-12-16 12:39 UTC, andy-bell101 commented
Ok I think everything works now

2022-12-17 01:40 UTC, rouge8 requested changes
This is great, thanks! Just going to remove some extra print statements

2022-12-17 01:40 UTC, rouge8 commented on tests/init_spec.lua
> +        print(vim.inspect(results))
```suggestion
```

2022-12-17 01:40 UTC, rouge8 commented on tests/init_spec.lua
> +        print(vim.inspect(expected))
```suggestion
```

2022-12-17 01:40 UTC, rouge8 approved these changes

2022-12-17 01:41 UTC, merged