fix: escape `$` for fish shells
rouge8/neotest-rust pull request #54
Opened 2023-09-19 23:07 UTC by realeinherjar

This closes #53.

2023-09-19 23:32 UTC, realeinherjar commented on lua/neotest-rust/init.lua
> +        test_filter = '-E "' .. package_filter .. "test(/^" .. position_id .. '$/)"'
What evil sorcery is this?

2023-09-20 00:33 UTC, rouge8 requested changes
Hmm I wondered about this when I merged #52, but I tested and it seemed to work... Can you fix the tests?

2023-09-20 04:30 UTC, rouge8 commented
Actually @realeinherjar can you test #55 and see if that resolves your issue?

2023-09-20 08:38 UTC, realeinherjar commented
Closing this in favor of #55

2023-09-20 08:38 UTC, closed without merging