Fix mod path when both mod file and mod dir exist
rouge8/neotest-rust pull request #68
Opened 2024-01-02 15:03 UTC by Frederick888

When both src/parent.rs and src/parent/ exist, construct_mod_path can be
called with construct_mod_path('src/parent.rs', 'child'). In this case
it should return src/parent/child.rs instead of nil.

Closes #60

2024-01-02 15:09 UTC, rouge8 requested changes
Please add a test

2024-01-03 01:46 UTC, Frederick888 commented
> Please add a test

Done 👌

2024-01-03 02:44 UTC, rouge8 approved these changes

2024-01-03 02:45 UTC, merged

2024-01-03 02:45 UTC, rouge8 commented
Thanks!